### ISSUE TITLE
Widget looses position after every reboot

### ISSUE THREAD

**Issue by kneckergit** [qewer33/ClearClock#10]
This might be more of an KDE plasma related issue with my dual monitor setup, but I report it nonetheless:
After every reboot, the widget gets placed at 0,0 (top left).

Kernel: 5.16.14-1-MANJARO x86_64
KDE Plasma: 5.24.3

**Comment by qewer33** [comment]
Seems like a Plasma bug, Plasma handles widget positions and layouts so not much I can do. Does it happen with any other widget?
https://bugs.kde.org/show_bug.cgi?id=413645
https://bugs.kde.org/show_bug.cgi?id=451487

**Comment by kneckergit** [comment]
Tested, and can confirm it is not a ClearClcok bug. It is one of the bugs mention above in plasma.
Thanks anyway!
