### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by zany130** [qewer33/ClearClock#15]
I see this hasn't recived updates in a while but is there a chance for this to be ported to plasma 6? Thanks.

**Comment by xkain** [comment]
Would be great to see this excellent widget ported to Plasma 6 !

**Comment by qewer33** [comment]
I'll definitely get to porting it but Exquisite is quite complex (uses a lot of different Qt and KDE APIs) and sadly KDE doesn't have any official KWin script porting guides or Plasma 6 API docs yet as far as I'm aware.

**Comment by xkain** [comment]
I'm really happy to learn that the port is planned, I miss this wonderful plasmoid a lot since switching to Plasma 6

I don't know if this will help but here is a link to the doc for porting to Plasma 6 : https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by qewer33** [comment]
> I'm really happy to learn that the port is planned, I miss this wonderful plasmoid a lot since switching to Plasma 6
> 
> I don't know if this will help but here is a link to the doc for porting to Plasma 6 : https://develop.kde.org/docs/plasma/widget/porting_kf6/

I just realized my comment here was related to another one of my projects. I'll take a look at the plasmoid porting docs, thanks!

**Comment by qewer33** [comment]
Plasma 6 is now supported!
https://www.pling.com/p/2147871/

Would appreciate any early testers.
