### ISSUE TITLE
[request] Your app is very nice, can you make a version for Windows?

### ISSUE THREAD

**Issue by Dhyfer1** [qewer33/ClearClock#17]
What the title says, I would like to see ClearClock also on Windows.

**Comment by qewer33** [comment]
There is a similar clock skin available for Rainmeter on Windows (made by someone else not me):

https://visualskins.com/skin/robik

**Comment by Dhyfer1** [comment]
I don't want skins, I want a widget, and thanks for showing me a new style that I want another dev to work on in another app

**Comment by Dhyfer1** [comment]
I don't want skins, I want a widget, and thanks for showing me a new style that I want another dev to work on in another app
