### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by alonsodonpedro** [qewer33/ClearClock#4]
In version 0.3, all configuration options in the Appearance tab disappeared.
![2022-01-04_18-50](https://user-images.githubusercontent.com/97121017/148102062-01dc2ba7-16d5-40a4-9c9e-e225df1fd1dc.jpg)

**Comment by qewer33** [comment]
Can you run this command from your home directory and send the output here?
`qmlscene .local/share/plasma/plasmoids/org.kde.plasma.clearclock/contents/ui/config/configAppearance.qml`

**Comment by alonsodonpedro** [comment]
[image: 2022-01-05_15-23.jpg]

śr., 5 sty 2022 o 15:11 qewer ***@***.***> napisał(a):

**Comment by alonsodonpedro** [comment]
![2022-01-05_15-23](https://user-images.githubusercontent.com/97121017/148233821-4ad0ecea-9cf9-4a2c-adaf-0a3c7013dd15.jpg)

**Comment by qewer33** [comment]
That is an interesting error, can you also provide your system information?

**Comment by alonsodonpedro** [comment]
Operating System: Kubuntu 21.10
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-23-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-4770 CPU @ 3.40GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4600

**Comment by qewer33** [comment]
Alright, this should be fixed now. Can you try updating the plasmoid and confirm it works?

**Comment by alonsodonpedro** [comment]
Now everything is fine.

**Comment by xakiy** [comment]
Hi, I tried your widget, looks nice but unfortunately the setting won't show up.

Tried to invoke 
`qmlscene ~/.local/share/plasma/plasmoids/org.kde.plasma.clearclock/contents/ui/config/configAppearance.qml `
it said
`file:///home/ghulam/.local/share/plasma/plasmoids/org.kde.plasma.clearclock/contents/ui/config/configAppearance.qml:8 module "QtQuick.Layouts" version 1.15 is not installed`

I have system with:
 Qt Version: 5.12.7
 KDE Plasma: 5.18.6
 KDE Frameworks Version: 5.76.0

I've changed all the QtQuick.Layouts 1.15 in the qml files to 1.12 and it works.
Made it as PR, hope you can  merge it.

**Comment by qewer33** [comment]
Merged, thanks for the PR!

**Comment by xakiy** [comment]
:+1:
