### ISSUE TITLE
Add option for seconds in clock display

### ISSUE THREAD

**Issue by NotAName320** [qewer33/ClearClock#5]
Hey! I've been using this as part of my Plasma configuration for a while as a replacement to the vanilla clock widget and I've been loving it. It would be cool if there was an option to let the widget track seconds under the "Use 24 hour clock" option, [like the vanilla clock allows](https://cdn.discordapp.com/attachments/395638697497985035/938506117804351569/unknown.png).

Thanks for creating the widget!

**Comment by qewer33** [comment]
Thanks for the suggestion! Added in the 0.4 release with commit 3300aeb

**Comment by NotAName320** [comment]
thanks
